"""Generated by AppCreator. Do not edit by hand."""

from __future__ import annotations

import sys
from pathlib import Path

from flask import Flask, jsonify, request
from flask_cors import CORS
from pydantic import ValidationError

SERVER_DIR = Path(__file__).resolve().parent
if str(SERVER_DIR) not in sys.path:
    sys.path.insert(0, str(SERVER_DIR))

from ApiRequest import ApiRequests, DuplicateEmailError, getServices
from Object import allowedDevOrigins, sessionCookieName

app = Flask(__name__)
app.config["JSON_SORT_KEYS"] = False

CORS(
    app,
    resources={r"/api/*": {"origins": list(allowedDevOrigins)}},
    supports_credentials=True,
)

api_requests = ApiRequests(services_provider=getServices)


def build_api_payload(result, success_message=None):
    if isinstance(result, dict):
        payload = dict(result)
    else:
        payload = {"data": result}
    if success_message:
        payload.setdefault("message", success_message)
    return payload


def build_api_response(result, success_message=None):
    return jsonify(build_api_payload(result, success_message=success_message))


def json_error(message, status_code):
    return jsonify({"error": message}), status_code


@app.route('/api/auth/change-password', methods=['POST'])
def handle_changePassword():
    payload = request.get_json(silent=True) or {}
    try:
        session = None
        token = request.cookies.get(sessionCookieName, '')
        session = api_requests.services.auth.getSession(token)
        if session is None:
            return json_error('Authentication required.', 401)
        current_user = session.user.id
        userId = payload.get('userId', current_user)
        currentPassword = payload.get('currentPassword')
        newPassword = payload.get('newPassword')
        confirmPassword = payload.get('confirmPassword')
        if userId != current_user:
            raise PermissionError('You do not have permission to access this resource.')
        result = api_requests.changePassword(userId, currentPassword, newPassword, confirmPassword)
        response = build_api_response(result, success_message='Password updated successfully')
        return response, 200
    except PermissionError as error:
        return json_error(str(error), 403)
    except ValidationError as error:
        return json_error(error.errors()[0]['msg'], 400)
    except DuplicateEmailError as error:
        return json_error(str(error), 409)
    except ValueError as error:
        return json_error(str(error), 400)
    except Exception as error:
        return json_error(str(error), 500)


@app.route('/api/tasks', methods=['DELETE'])
def handle_clearCompleted():
    payload = request.get_json(silent=True) or {}
    try:
        session = None
        token = request.cookies.get(sessionCookieName, '')
        session = api_requests.services.auth.getSession(token)
        if session is None:
            return json_error('Authentication required.', 401)
        current_user = session.user.id
        userId = payload.get('userId', current_user)
        if userId != current_user:
            raise PermissionError('You do not have permission to access this resource.')
        result = api_requests.clearCompleted(userId)
        response = build_api_response(result, success_message='Completed tasks cleared successfully')
        return response, 200
    except PermissionError as error:
        return json_error(str(error), 403)
    except ValidationError as error:
        return json_error(error.errors()[0]['msg'], 400)
    except DuplicateEmailError as error:
        return json_error(str(error), 409)
    except ValueError as error:
        return json_error(str(error), 400)
    except Exception as error:
        return json_error(str(error), 500)


@app.route('/api/tasks', methods=['POST'])
def handle_createTask():
    payload = request.get_json(silent=True) or {}
    try:
        session = None
        token = request.cookies.get(sessionCookieName, '')
        session = api_requests.services.auth.getSession(token)
        if session is None:
            return json_error('Authentication required.', 401)
        current_user = session.user.id
        userId = payload.get('userId', current_user)
        title = payload.get('title')
        notes = payload.get('notes', '')
        category = payload.get('category', '')
        priority = payload.get('priority', 'medium')
        dueDate = payload.get('dueDate')
        dueTime = payload.get('dueTime')
        completed = payload.get('completed', False)
        if userId != current_user:
            raise PermissionError('You do not have permission to access this resource.')
        result = api_requests.createTask(userId, title, notes, category, priority, dueDate, dueTime, completed)
        response = build_api_response(result, success_message='Task created successfully')
        return response, 201
    except PermissionError as error:
        return json_error(str(error), 403)
    except ValidationError as error:
        return json_error(error.errors()[0]['msg'], 400)
    except DuplicateEmailError as error:
        return json_error(str(error), 409)
    except ValueError as error:
        return json_error(str(error), 400)
    except Exception as error:
        return json_error(str(error), 500)


@app.route('/api/tasks/<taskId>', methods=['DELETE'])
def handle_deleteTask(taskId):
    payload = request.get_json(silent=True) or {}
    try:
        session = None
        token = request.cookies.get(sessionCookieName, '')
        session = api_requests.services.auth.getSession(token)
        if session is None:
            return json_error('Authentication required.', 401)
        current_user = session.user.id
        userId = payload.get('userId', current_user)
        if userId != current_user:
            raise PermissionError('You do not have permission to access this resource.')
        result = api_requests.deleteTask(userId, taskId)
        response = build_api_response(result, success_message='Task deleted successfully')
        return response, 200
    except PermissionError as error:
        return json_error(str(error), 403)
    except ValidationError as error:
        return json_error(error.errors()[0]['msg'], 400)
    except DuplicateEmailError as error:
        return json_error(str(error), 409)
    except ValueError as error:
        return json_error(str(error), 400)
    except Exception as error:
        return json_error(str(error), 500)


@app.route('/api/auth/session', methods=['GET'])
def handle_getSession():
    payload = request.get_json(silent=True) or {}
    try:
        session = None
        token = request.cookies.get(sessionCookieName, '')
        if token:
            session = api_requests.services.auth.getSession(token)
        if session is None:
            return json_error('Authentication required.', 401)
        result = api_requests.getSession(token)
        response = build_api_response(result, success_message=None)
        return response, 200
    except PermissionError as error:
        return json_error(str(error), 403)
    except ValidationError as error:
        return json_error(error.errors()[0]['msg'], 400)
    except DuplicateEmailError as error:
        return json_error(str(error), 409)
    except ValueError as error:
        return json_error(str(error), 400)
    except Exception as error:
        return json_error(str(error), 500)


@app.route('/api/tasks', methods=['GET'])
def handle_getTasks():
    payload = request.get_json(silent=True) or {}
    try:
        session = None
        token = request.cookies.get(sessionCookieName, '')
        session = api_requests.services.auth.getSession(token)
        if session is None:
            return json_error('Authentication required.', 401)
        current_user = session.user.id
        userId = payload.get('userId', current_user)
        if userId != current_user:
            raise PermissionError('You do not have permission to access this resource.')
        result = api_requests.getTasks(userId)
        response = build_api_response(result, success_message=None)
        return response, 200
    except PermissionError as error:
        return json_error(str(error), 403)
    except ValidationError as error:
        return json_error(error.errors()[0]['msg'], 400)
    except DuplicateEmailError as error:
        return json_error(str(error), 409)
    except ValueError as error:
        return json_error(str(error), 400)
    except Exception as error:
        return json_error(str(error), 500)


@app.route('/api/health', methods=['GET'])
def handle_health():
    payload = request.get_json(silent=True) or {}
    try:
        session = None
        token = request.cookies.get(sessionCookieName, '')
        result = api_requests.health()
        response = build_api_response(result, success_message=None)
        return response, 200
    except PermissionError as error:
        return json_error(str(error), 403)
    except ValidationError as error:
        return json_error(error.errors()[0]['msg'], 400)
    except DuplicateEmailError as error:
        return json_error(str(error), 409)
    except ValueError as error:
        return json_error(str(error), 400)
    except Exception as error:
        return json_error(str(error), 500)


@app.route('/api/auth/login', methods=['POST'])
def handle_login():
    payload = request.get_json(silent=True) or {}
    try:
        session = None
        token = request.cookies.get(sessionCookieName, '')
        email = payload.get('email')
        password = payload.get('password')
        result = api_requests.login(email, password)
        response = build_api_response(result, success_message='Login successful')
        token_value = response.get_json().get('token', '')
        if token_value:
            response.set_cookie(
                sessionCookieName,
                token_value,
                httponly=True,
                samesite='Lax',
                secure=False,
                max_age=30 * 24 * 60 * 60,
            )
        return response, 200
    except PermissionError as error:
        return json_error(str(error), 403)
    except ValidationError as error:
        return json_error(error.errors()[0]['msg'], 400)
    except DuplicateEmailError as error:
        return json_error(str(error), 409)
    except ValueError as error:
        return json_error(str(error), 400)
    except Exception as error:
        return json_error(str(error), 500)


@app.route('/api/auth/logout', methods=['POST'])
def handle_logout():
    payload = request.get_json(silent=True) or {}
    try:
        session = None
        token = request.cookies.get(sessionCookieName, '')
        session = api_requests.services.auth.getSession(token)
        if session is None:
            return json_error('Authentication required.', 401)
        current_user = session.user.id
        userId = payload.get('userId', current_user)
        if userId != current_user:
            raise PermissionError('You do not have permission to access this resource.')
        result = api_requests.logout(userId, token)
        response = build_api_response(result, success_message='Logged out successfully')
        response.delete_cookie(sessionCookieName, httponly=True, samesite='Lax', secure=False)
        return response, 200
    except PermissionError as error:
        return json_error(str(error), 403)
    except ValidationError as error:
        return json_error(error.errors()[0]['msg'], 400)
    except DuplicateEmailError as error:
        return json_error(str(error), 409)
    except ValueError as error:
        return json_error(str(error), 400)
    except Exception as error:
        return json_error(str(error), 500)


@app.route('/api/auth/register', methods=['POST'])
def handle_registerUser():
    payload = request.get_json(silent=True) or {}
    try:
        session = None
        token = request.cookies.get(sessionCookieName, '')
        name = payload.get('name')
        email = payload.get('email')
        password = payload.get('password')
        result = api_requests.registerUser(name, email, password)
        response = build_api_response(result, success_message='Registration successful')
        token_value = response.get_json().get('token', '')
        if token_value:
            response.set_cookie(
                sessionCookieName,
                token_value,
                httponly=True,
                samesite='Lax',
                secure=False,
                max_age=30 * 24 * 60 * 60,
            )
        return response, 201
    except PermissionError as error:
        return json_error(str(error), 403)
    except ValidationError as error:
        return json_error(error.errors()[0]['msg'], 400)
    except DuplicateEmailError as error:
        return json_error(str(error), 409)
    except ValueError as error:
        return json_error(str(error), 400)
    except Exception as error:
        return json_error(str(error), 500)


@app.route('/api/tasks/<taskId>', methods=['PATCH'])
def handle_updateTask(taskId):
    payload = request.get_json(silent=True) or {}
    try:
        session = None
        token = request.cookies.get(sessionCookieName, '')
        session = api_requests.services.auth.getSession(token)
        if session is None:
            return json_error('Authentication required.', 401)
        current_user = session.user.id
        userId = payload.get('userId', current_user)
        title = payload.get('title')
        notes = payload.get('notes')
        category = payload.get('category')
        priority = payload.get('priority')
        dueDate = payload.get('dueDate')
        dueTime = payload.get('dueTime')
        completed = payload.get('completed')
        if userId != current_user:
            raise PermissionError('You do not have permission to access this resource.')
        result = api_requests.updateTask(userId, taskId, title, notes, category, priority, dueDate, dueTime, completed)
        response = build_api_response(result, success_message='Task updated successfully')
        return response, 200
    except PermissionError as error:
        return json_error(str(error), 403)
    except ValidationError as error:
        return json_error(error.errors()[0]['msg'], 400)
    except DuplicateEmailError as error:
        return json_error(str(error), 409)
    except ValueError as error:
        return json_error(str(error), 400)
    except Exception as error:
        return json_error(str(error), 500)


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000, debug=True)
